FROM node:21-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY src/prisma/schema.prisma src/prisma/schema.prisma

RUN npm install 

RUN npx prisma generate --schema=src/prisma/schema.prisma

RUN npm install --save-dev tsx

COPY . .
RUN find src -type f -name "*.js" -delete

EXPOSE 3000
CMD ["npm","run","dev"]

